# OldCombatMechanics Plugin by kernitus and Rayzr522
#Bukkit Page: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics/
#Spigot Page: https://www.spigotmc.org/resources/oldcombatmechanics.19510/
#GitHub Page: https://github.com/kernitus/BukkitOldCombatMechanics/

# This is to toggle the plugin's main functionality on/off
plugin-active: true

# This is to toggle the update checker
update-checker: true

# This is to disable player collisions
disable-player-collisions: false

# This is to set the axe damage as in pre-1.9
old-axe-damage: false

# This is to disable the special sword attack that knocks back
disable-knockback-attack: false

# This is to disable the use of shields
disable-shields: false